# GitHub Dependabot configuration for Teams.ThirdPartyAppApi
# This file configures Dependabot to automatically check for dependency updates

version: 2
updates:
  # Enable version updates for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ferenyl"
    assignees:
      - "ferenyl"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    # Group minor and patch updates for better PR management
    groups:
      production-dependencies:
        patterns:
          - "Microsoft.Extensions.*"
          - "System.*"
          - "Macross.*"
        update-types:
          - "minor"
          - "patch"
      test-dependencies:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "xunit*"
          - "Moq"
          - "coverlet.*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ferenyl"
    assignees:
      - "ferenyl"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
