# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Core CI

on:
  push:
    branches: ["*"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Detect prerelease from tag
        id: branch_check
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          IS_PRERELEASE="false"
          if [[ "$TAG_VERSION" == *-* ]]; then
            IS_PRERELEASE="true"
          fi
          echo "IS_PRERELEASE=$IS_PRERELEASE" >> $GITHUB_OUTPUT
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Get version
        id: get_version
        run: |
          VERSION="${{ steps.branch_check.outputs.TAG_VERSION }}"
          echo "NEW_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set version to tag or prerelease
        id: bump_version
        env:
          NEW_VERSION: ${{ steps.get_version.outputs.NEW_VERSION }}
        run: |
          # Sätt Version till hela taggen
          sed -i "s/<Version>.*<\/Version>/<Version>$NEW_VERSION<\/Version>/g" ./src/Teams.ThirdPartyAppApi.csproj
          # Sätt AssemblyVersion och FileVersion till stabil version (utan prerelease)
          STABLE_VERSION=$(echo "$NEW_VERSION" | cut -d'-' -f1)
          sed -i "s/<AssemblyVersion>.*<\/AssemblyVersion>/<AssemblyVersion>$STABLE_VERSION.0<\/AssemblyVersion>/g" ./src/Teams.ThirdPartyAppApi.csproj
          sed -i "s/<FileVersion>.*<\/FileVersion>/<FileVersion>$STABLE_VERSION.0<\/FileVersion>/g" ./src/Teams.ThirdPartyAppApi.csproj
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Pack
        run: dotnet pack ./src/Teams.ThirdPartyAppApi.csproj  --configuration Release --output ./artifacts
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Get NuGet package name
        id: pkg
        run: echo "PACKAGENAME=$(basename $(find ./artifacts -name '*.nupkg'))" >> $GITHUB_OUTPUT
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Generate release notes
        id: release_notes
        run: |
          RELEASE_NOTES="$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s")"
          echo  "NOTES=$RELEASE_NOTES" >> $GITHUB_OUTPUT
        if: startsWith(github.ref, 'refs/tags/v')

      - name: create release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "./artifacts/*.nupkg, ./artifacts/*.snupkg"
          body: ${{ steps.release_notes.outputs.NOTES }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.get_version.outputs.NEW_VERSION }}
          prerelease: ${{ steps.branch_check.outputs.IS_PRERELEASE }}
          draft: false
          name: Release v${{ steps.get_version.outputs.NEW_VERSION }}
          generateReleaseNotes: true
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Push
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        if: startsWith(github.ref, 'refs/tags/v')
